accelerate launch --mixed_precision="fp16" src/sd_ip2p_train/train_ip2p_transfer.py \
    --pretrained_model_name_or_path="timbrooks/instruct-pix2pix" \
    --pretrained_clip_path="clip_ckpt/clip_epoch_35" \
    --dataset_name="timbrooks/instructpix2pix-clip-filtered" \
    --cache_dir="/ibex/project/c2280/.cache/huggingface/datasets/ip2p" \
    --report_to="wandb" \
    --resolution=256 \
    --random_flip \
    --train_batch_size=64 \
    --gradient_accumulation_steps=1 \
    --gradient_checkpointing \
    --max_train_steps=20000 \
    --checkpointing_steps=2000 \
    --checkpoints_total_limit=10 \
    --learning_rate=5e-05 \
    --max_grad_norm=1 \
    --lr_warmup_steps=0 \
    --conditioning_dropout_prob=0.05 \
    --seed=42 \
    --validation_steps 500 \
    --dataloader_num_workers 3 \
    --is_use_projection_model \
    --lambda_lpips 0.05 \
    --lambda_diffusion 1